import type { Topic } from '@/types/debate';

export const TOPICS: readonly Topic[] = [
  // Fun & Everyday
  {
    id: 'pizza-lunch',
    text: 'Should school lunches include pizza every day?',
    category: 'fun',
    emoji: '🍕',
    hint: 'Think about: nutrition, variety, and what makes kids happy vs. healthy.',
  },
  {
    id: 'hotdog-sandwich',
    text: 'Is a hot dog a sandwich?',
    category: 'fun',
    emoji: '🌭',
    hint: 'Think about: what makes a sandwich a sandwich — bread, filling, shape?',
  },
  {
    id: 'paid-grades',
    text: 'Should kids get paid for good grades?',
    category: 'fun',
    emoji: '💰',
    hint: 'Think about: motivation, fairness, and learning for the right reasons.',
  },
  {
    id: 'summer-winter',
    text: 'Is summer better than winter?',
    category: 'fun',
    emoji: '☀️',
    hint: 'Think about: activities, weather, holidays, and how seasons make you feel.',
  },
  {
    id: 'recess-length',
    text: 'Should recess be longer than class time?',
    category: 'fun',
    emoji: '⏰',
    hint: 'Think about: focus, exercise, socializing, and how breaks help learning.',
  },
  // School Life
  {
    id: 'homework',
    text: 'Should schools have homework?',
    category: 'school',
    emoji: '📚',
    hint: 'Think about: practice, free time, stress, and whether learning stops at school.',
  },
  {
    id: 'choose-classes',
    text: 'Should students choose their own classes?',
    category: 'school',
    emoji: '🎒',
    hint: 'Think about: interests, well-rounded education, and responsibility.',
  },
  {
    id: 'later-start',
    text: 'Should school start later in the morning?',
    category: 'school',
    emoji: '😴',
    hint: 'Think about: sleep, schedules, after-school activities, and focus.',
  },
  {
    id: 'phones-school',
    text: 'Should phones be allowed in school?',
    category: 'school',
    emoji: '📱',
    hint: 'Think about: distractions, emergencies, learning tools, and self-control.',
  },
  {
    id: 'gym-graded',
    text: 'Should gym class be graded?',
    category: 'school',
    emoji: '🏃',
    hint: 'Think about: effort vs. ability, fairness, and why we have PE.',
  },

  // Big Ideas
  {
    id: 'zoos',
    text: 'Should zoos exist?',
    category: 'big-ideas',
    emoji: '🦁',
    hint: 'Think about: animal welfare, conservation, education, and natural habitats.',
  },
  {
    id: 'cats-vs-dogs',
    text: 'Are cats better pets than dogs?',
    category: 'big-ideas',
    emoji: '🐱',
    hint: 'Think about: care, companionship, independence, and what "better" means.',
  },
  {
    id: 'kids-vote',
    text: 'Should kids be allowed to vote?',
    category: 'big-ideas',
    emoji: '🗳️',
    hint: 'Think about: maturity, whose future it is, and understanding issues.',
  },
  {
    id: 'book-street-smart',
    text: 'Is it better to be book-smart or street-smart?',
    category: 'big-ideas',
    emoji: '🧠',
    hint: 'Think about: school knowledge vs. real-world skills, and which helps more.',
  },
  {
    id: 'learn-to-code',
    text: 'Should everyone learn to code?',
    category: 'big-ideas',
    emoji: '💻',
    hint: 'Think about: future jobs, problem-solving, and whether it\'s like learning math.',
  },
  // Anime
  {
    id: 'goku-vs-luffy',
    text: 'Is Goku stronger than Luffy?',
    category: 'anime',
    emoji: '💥',
    hint: 'Think about: raw power, transformations, willpower, and fighting styles.',
  },
  {
    id: 'vegeta-better-saiyan',
    text: 'Is Vegeta a better Saiyan than Goku?',
    category: 'anime',
    emoji: '🔥',
    hint: 'Think about: pride, training, sacrifice, and what "better" really means.',
  },
  {
    id: 'goku-second-chances',
    text: 'Should Goku stop giving villains second chances?',
    category: 'anime',
    emoji: '🤔',
    hint: 'Think about: mercy, risk, redemption, and whether it ever backfires.',
  },
  {
    id: 'devil-fruit-or-swim',
    text: 'Would you rather have a Devil Fruit power or be able to swim?',
    category: 'anime',
    emoji: '🌊',
    hint: 'Think about: what you\'d gain vs. lose, and how often you\'d need water.',
  },
  {
    id: 'luffy-bravest-captain',
    text: 'Is Luffy the bravest anime captain ever?',
    category: 'anime',
    emoji: '🏴‍☠️',
    hint: 'Think about: recklessness vs. bravery, and other captains to compare.',
  },
  {
    id: 'power-of-friendship',
    text: 'Can the power of friendship really beat any villain?',
    category: 'anime',
    emoji: '💪',
    hint: 'Think about: teamwork, plot armor, and when friendship isn\'t enough.',
  },
  {
    id: 'natsu-vs-gray',
    text: 'Is Natsu stronger than Gray?',
    category: 'anime',
    emoji: '🐉',
    hint: 'Think about: fire vs. ice, emotions in battle, and their best fights.',
  },
  {
    id: 'ban-immortality',
    text: "Is Ban's immortality more of a curse than a gift?",
    category: 'anime',
    emoji: '♾️',
    hint: 'Think about: watching others age, pain without end, and what makes life valuable.',
  },
  {
    id: 'seven-deadly-sins-heroes',
    text: 'Are the Seven Deadly Sins actually heroes?',
    category: 'anime',
    emoji: '⚔️',
    hint: 'Think about: their past crimes, redemption, and what makes someone a hero.',
  },
  {
    id: 'tanjiro-too-kind',
    text: 'Is Tanjiro too kind to be a great demon slayer?',
    category: 'anime',
    emoji: '🗡️',
    hint: 'Think about: empathy as strength or weakness, and mercy toward enemies.',
  },
  {
    id: 'zenitsu-brave',
    text: 'Is Zenitsu actually braver than he thinks?',
    category: 'anime',
    emoji: '⚡',
    hint: 'Think about: fear vs. courage, acting despite fear, and what bravery means.',
  },
] as const;

export const CATEGORY_LABELS: Record<Topic['category'], string> = {
  fun: '🍕 Fun & Everyday',
  school: '🏫 School Life',
  'big-ideas': '🌍 Big Ideas',
  anime: '⚔️ Anime Battles',
};
